```{=html}
<!--

Skripte für die Übungen 02 des Moduls FPM08 Forstliche Fernerkundung im Studiengang
B.Sc. Forstwirtschaft an der HAWK Göttingen.

Autor: Paul Magdon
Datum: 2025-10-12
Letztes Update: 2026-10-08 (Hans Fuchs)
Lizenz: Creative Commons BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/

-->
```
# Lerneinheit 01: Erste Schritte in QGIS
## Lernziele & Aufgabenstellung

Die erste Lerneinheit dient der Einrichtung einer Arbeitsumgebung und Wiederholung wesentlicher QGIS-Funktionen. 
Wir prüfen die Installation der Programme und QGIS-Erweiterungen. Es wird außerdem gezeigt, wie wir 
Einstellungen in den persönlichen QGIS-Profilen speichern und sichern können. 

**Lernziele**

Die Studierenden sollen:

-   QGIS installieren und überprüfen welche Version installiert ist
-   die Funktionsweise von Benutzerprofilen verstehen und anwenden
-   eine sinnvolle Ordnerstruktur zur Verwaltung von QGIS-Projekten kennen und anlegen
-   Projekte in QGIS anlegen

**Aufgabenstellung**

1.  Überprüfen Sie die Installation von QGIS und EnMAP-Box Plugin.

2.  Legen Sie ein neues QGIS Benutzerprofil mit ihrem Namen an.

3.  Installieren Sie das EnMAP-Box-Plugin und zusätzliche Module.

4.  Sichern Sie ihr QGIS Benutzerprofil an einem permanenten Speicherort.

5.  Legen Sie eine Ordnerstruktur für das Projekt uebung01 an.

6.  Legen Sie innerhalb der Ordnerstruktur eine neues QGIS-Projekt *`uebung01.qgz`* an.

## QGIS und EnMAP-Box Installation

### Installation von QGIS {#sec-qgisinstall}
Die vorgestellten Programme funktionieren grundsätzlich unter Windows, MacOS und Linux Betriebssystemen.

::: {.panel-tabset}

## Windows
::: callout-note
Im PC-Pool der HAWK ist QGIS bereits auf den Computern installiert. Das EnMAP-Box-Plugin muss zusätzlich in das persönliche QGIS Benutzerprofil installiert werden. Eine vollständige Installation von QGIS und EnMAP-Box ist notwendig, wenn Sie die Übungen auf einem eigenen Computer durchführen wollen. 
:::

In diesem Kurs wird die Software QGIS in der Version 3.40.8 verwendet. Sie können die Software hier
herunterladen:

<https://qgis.org/downloads/QGIS-OSGeo4W-3.40.8-1.msi>

Der aktuelle Windows Standalone Installer für QGIS LTR (Long Term Release) 3.44 sollte auch funktionieren und kann hier heruntergeladen werden: <https://qgis.org/download/>

## MacOS

Auf Apple Laptops mit MacOS High Sierra (10.14) oder neuere Versionen können Sie den offiziellen MacOS installer für QGIS LTR 3.44 von der [QGIS Download Seite](https://qgis.org/download/) verwenden. Laden Sie die `.dmg` Datei herunter, öffnen Sie sie und ziehen Sie QGIS in den Applications Ordner.

## Linux
Ausführliche QGIS Installationsanweisungen für verschiedene Linux Distributionen finden Sie auf <https://qgis.org/resources/installation-guide/>. Wählen Sie ein Long Term Release Repository mit der QGIS Version 3.44. 
:::

### Anlegen eines persönlichen QGIS-Benutzerprofils

QGIS kann auf eigene Bedürfnisse umfangreich angepasst werden. Dazu zählen z.B. folgende
Einstellungen:

-   Sprache
-   Projektionen und Koordinatensysteme
-   Passwörter für Datenbankzugänge
-   Anpassungen des Erscheinungsbildes und der dargestellten Werkzeuge
-   Installation und Konfiguration von Plugins

::: callout-note
Das Anlegen persönlicher Benutzerprofile geschieht in der Regel vollständig automatisch. Im PC-Pool
werden diese Profile aber nicht zwischen den PC-Arbeitsplätzen synchronisiert. Außerdem werden die
lokalen Benutzerdaten in regelmäßigen Abständen gelöscht. Daher kann es für die Arbeit im PC-Pool
sinnvoll sein, ein eigenes Profil anzulegen und in einem persönlichen Ordner zu sichern.
:::

QGIS speichert Benutzerprofile automatisch im lokalen Profilordner:

- auf Windows: `C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\`

- auf MacOS: `/Users/USERNAME/Library/Application Support/QGIS/QGIS3/profiles/`

- auf Linux: `/home/USERNAME/.local/share/QGIS/QGIS3/profiles/`

USERNAME steht hier als Platzhalter für Ihren Benutzernamen, also den aktuell angemeldeten Benutzernamen.
Das Verzeichnis, in dem die QGIS Benutzerprofile gespeichert werden, lässt sich direkt im QGIS Hauptmenü öffnen mit

`Einstellungen` → `Benutzerprofile` → `Aktuelles Profilverzeichnis öffnen`

Standardmäßig gibt es in QGIS nur das Benutzerprofil *default*. Es können aber beliebig viele zusätzlich angelegt werden.

::: {style="border: 2px solid #afca0b; background-color: ; padding: 8px;"}
Legen Sie ein neues Nutzerprofile mit Ihrem Namen (z.B. mueller) an:

`Einstellungen` → `Benutzerprofile` → `Neues Profil anlegen`
:::

Weitere Informationen zu den QGIS-Benutzerprofilen finden sie hier:
<https://docs.qgis.org/3.40/de/docs/user_manual/introduction/qgis_configuration.html#user-profiles>

### Installation des EnMAP-Box Plugins und zusätzlicher Module {#sec-enmap}

Neben QGIS nutzen wir für die fernerkundlichen Auswertungen das quelloffene QGIS Plugin [EnMAP-Box](https://enmap-box.readthedocs.io/en/latest/general/about.html) in der Version 3.17.9.

#### Installation der EnMAP-Box Erweiterung

::: {style="border: 2px solid #afca0b; background-color: #fafafa; padding: 8px;"}
`Erweiterungen` → `Erweiterungen verwalten und installieren`

Im Suchfenster `enmap`  eingeben, das angezeigte Plugin `EnMAP-Box 3`auswählen und installieren.

:::

#### Installation zusätzlicher EnMAP-Box Module

::: {.panel-tabset}

## Windows
Nachdem das Plugin installiert ist, müssen noch zusätzliche Module installiert werden bevor es gestartet werden kann. 

- Laden Sie das Installationskript [installation_qgis_dependencies_base.py](https://cloud.hawk.de/index.php/s/CwTKje2HLo2RZHX)
herunter und speichern Sie es direkt in das lokale Verzeichnis `D:\`

- Öffen Sie die QGIS Python Konsole: `Erweiterungen` → `Python Konsole`

- Kopieren und Einfügen des folgenden Einzeilers in die Python Konsole, eventuell nur den Pfad zum heruntergeladenen Skript editieren,  dann Enter drücken zum Ausführen des Skriptes.

::: {style="border: 2px solid #afca0b; background-color: #e0e0e0; padding: 8px;"}
```markdown
script=r"D:/install_qgis_dependencies_base.py"; exec(open(script,encoding="utf-8").read()); main([])
```
:::

- QGIS schliessen und neustarten.

- Starten Sie die EnMAP-Box: `Raster` → `EnMAP-Box` →  `EnMAP-Box`

## MacOS

Nachdem das Plugin installiert ist, müssen auch auf Apple MacOS Laptops noch zusätzliche Module installiert werden bevor es gestartet werden kann.

- Öffen Sie die QGIS Python Konsole: `Erweiterungen` → `Python Konsole`

- Öffnen Sie den Editor innerhalb der Python Konsole um mehrzeiligen Code auf einmal auszuführen.

- Kopieren und Einfügen des gesamten folgenden Code Blocks in den Editor der Python Konsole.

::: {style="border: 2px solid #afca0b; background-color: #e0e0e0; padding: 8px;"}
```markdown
import sys
import os
import runpy

# Create the missing bin directory (otherwise pip aborts on console-script packages)
broken_bin_path = "/Applications/QGIS.app/Contents/Frameworks/bin"
os.makedirs(broken_bin_path, exist_ok=True)
print("Created missing bin directory. Starting installation...")

original_argv = sys.argv

enmap_packages = [
    # Command 1 - basic packages
    "colorama",
    "astropy",
    "PyOpenGL",
    "xgboost",
    "lightgbm",
    "catboost",
    "sympy",
    "numba>=0.57",
    "scikit-learn>=1.0",
    "defusedxml",
    "pyqtgraph",
    "skops",
    "netCDF4",
]

# Install all packages in one go
sys.argv = [
    "pip",
    "install",
    "-U",
    "--no-warn-script-location",
] + enmap_packages

try:
    runpy.run_module("pip", run_name="__main__")
except SystemExit:
    pass
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    sys.argv = original_argv
    print("=========================================")
    print("All packages are now fully installed!")
    print("You can safely activate EnMAP-Box 3.")
    print("=========================================")
```
:::
- Auf auf den grünen Pfeil des Editors klicken zum Ausführen.

- QGIS schliessen und neustarten.

- Starten Sie die EnMAP-Box: `Raster` → `EnMAP-Box` →  `EnMAP-Box`

Falls diese Installation auf Ihrem Macbook nicht funktioniert, können Sie alternativ QGIS und EnMap-Box auch in einer `Conda` Umgebung nach dieser Anleitung installieren: <https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html>

## Linux
Nachdem das Plugin installiert ist, müssen noch zusätzliche Module installiert werden bevor es gestartet werden kann. 

- Laden Sie das Installationskript [installation_qgis_dependencies_base.py](https://cloud.hawk.de/index.php/s/CwTKje2HLo2RZHX)
herunter und speichern Sie es in ein lokales Verzeichnis z.B. unter Downloads.

- Öffen Sie die QGIS Python Konsole: `Erweiterungen` → `Python Konsole`

- Kopieren und Einfügen des folgenden Einzeilers in die Python Konsole, passen Sie den Pfad zum heruntergeladenen Skript an, dann Enter drücken zum Ausführen des Skriptes.

::: {style="border: 2px solid #afca0b; background-color: #e0e0e0; padding: 8px;"}
```markdown
script=r"/home/USERNAME/Downloads/install_qgis_dependencies_base.py"; exec(open(script,encoding="utf-8").read()); main([])
```
:::

- QGIS schliessen und neustarten.

- Starten Sie die EnMAP-Box: `Raster` → `EnMAP-Box` →  `EnMAP-Box`

:::


### Sichern des persönlichen Nutzerprofils {#sec-nutzerprofil}

Nach dem nun die wichtigsten Einstellungen vorgenommen und im QGIS-Benutzerprofil hinterlegt wurden,
ist es sinnvoll dieses für die spätere Verwendung im **PC-Pool der HAWK** zu sichern. Auf ihren persönlichen Laptops brauchen Sie diesen Schritt nicht durchzuführen. 

::: {style="border: 2px solid #afca0b; background-color: #fafafa; padding: 8px;"}
Sichern sie den gesamten Ordner `QGIS3` mit Ihren persönlichen Profildaten (`C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3`) in
ihr persönliches Laufwerk unter `U:\`
:::

Sollten sie im späteren Verlauf des Kurses ihre Profile wiederherstellen wollen, können sie den
Ordner `QGIS3` von `U:\` wieder in den QGIS-Profil Ordner `C:\Users\USERNAME\AppData\Roaming\QGIS\` kopieren.

## Projekt- und Datenmanagement mit QGIS {#sec-projekt_management}

### Anlegen einer Ordnerstruktur

Eine gute Ordnerstruktur ist für das Datenmanagement sehr hilfreich. Daher wird empfohlen für jedes
Projekt bzw. jede Lerneinheit eine eigene Ordnerstruktur nach einheitlichem Muster anzulegen. Die
Struktur könnte so aussehen:

``` plaintext
projekt_xy/
├── daten/
│   └── raster_1.tif
|   └── raster_2.tif
├── karten/
│   └── baumartenkarte.pdf
└── projekt_XY.qgz
```

Diese Ordnerstruktur kann an die eigenen Präferenzen und die Notwendigkeiten im Projekt angepasst werden. Diese Struktur ist vorteilhaft, weil der gesamte Ordner verschoben, kopiert oder mit anderen geteilt werden kann. Dies ist möglich, da die Projektdatei relative Pfade speichert, ausgehend von dem Ordner in dem die *\*.qgz* Datei liegt, also z.B. *`./daten/raster_1.tif`*

### Anlegen eines neuen QGIS-Projektes

In QGIS können einzelne Projekte z.B. eine Lehreinheit als Projekte angelegt und gespeichert werden. Dabei werden sämtliche Einstellungen und Darstellungen (z.B. Kartenlayouts, Symbologien, Layer), Bearbeitungsstand und vieles mehr gespeichert. Das ist vor allem sinnvoll wenn man seine Arbeit unterbrechen und zu einem späteren Zeitpunkt fortsetzen möchte. Die Projekte werden in einer Datei mit der Endung \*.qgz gespeichert.

::: callout-note
Die Projektdatei \*.qgz enthält nicht die Geodaten, des Projektes. Es werden lediglich die Pfade zu den Dateien mit den Geodaten gespeichert. Beim Laden des Projektes werden die Geodaten an den hinterlegten Datenpfaden gesucht und geladen. Sollten diese nicht mehr an dem Ort gespeichert sein, erscheint in QGIS eine Fehlermeldung. Eine klare Ordnerstruktur kann solche Fehler vermeiden helfen.
:::
